// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: giltconsensusv2/stake/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgApproveValidator defines a validator vote for native Gold Chain validator
// admission proposals.
type MsgApproveValidator struct {
	From            string                `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	ValId           uint64                `protobuf:"varint,2,opt,name=val_id,json=valId,proto3" json:"val_id,omitempty"`
	Operator        string                `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	ActivationEpoch uint64                `protobuf:"varint,4,opt,name=activation_epoch,json=activationEpoch,proto3" json:"activation_epoch,omitempty"`
	MaxGiltStake    cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=max_gilt_stake,json=maxGiltStake,proto3,customtype=cosmossdk.io/math.Int" json:"max_gilt_stake"`
	SignerPubKey    []byte                `protobuf:"bytes,6,opt,name=signer_pub_key,json=signerPubKey,proto3" json:"signer_pub_key,omitempty"`
	Nonce           uint64                `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *MsgApproveValidator) Reset()         { *m = MsgApproveValidator{} }
func (m *MsgApproveValidator) String() string { return proto.CompactTextString(m) }
func (*MsgApproveValidator) ProtoMessage()    {}
func (*MsgApproveValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{0}
}
func (m *MsgApproveValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveValidator.Merge(m, src)
}
func (m *MsgApproveValidator) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveValidator.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveValidator proto.InternalMessageInfo

func (m *MsgApproveValidator) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgApproveValidator) GetValId() uint64 {
	if m != nil {
		return m.ValId
	}
	return 0
}

func (m *MsgApproveValidator) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgApproveValidator) GetActivationEpoch() uint64 {
	if m != nil {
		return m.ActivationEpoch
	}
	return 0
}

func (m *MsgApproveValidator) GetSignerPubKey() []byte {
	if m != nil {
		return m.SignerPubKey
	}
	return nil
}

func (m *MsgApproveValidator) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

// MsgApproveValidatorResponse defines the response for MsgApproveValidator.
type MsgApproveValidatorResponse struct {
}

func (m *MsgApproveValidatorResponse) Reset()         { *m = MsgApproveValidatorResponse{} }
func (m *MsgApproveValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgApproveValidatorResponse) ProtoMessage()    {}
func (*MsgApproveValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{1}
}
func (m *MsgApproveValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveValidatorResponse.Merge(m, src)
}
func (m *MsgApproveValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveValidatorResponse proto.InternalMessageInfo

// MsgWithdrawValidatorStake releases self-bonded GILT after validator exit and
// unbonding have completed.
type MsgWithdrawValidatorStake struct {
	From  string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	ValId uint64 `protobuf:"varint,2,opt,name=val_id,json=valId,proto3" json:"val_id,omitempty"`
}

func (m *MsgWithdrawValidatorStake) Reset()         { *m = MsgWithdrawValidatorStake{} }
func (m *MsgWithdrawValidatorStake) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawValidatorStake) ProtoMessage()    {}
func (*MsgWithdrawValidatorStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{2}
}
func (m *MsgWithdrawValidatorStake) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawValidatorStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawValidatorStake.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawValidatorStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawValidatorStake.Merge(m, src)
}
func (m *MsgWithdrawValidatorStake) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawValidatorStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawValidatorStake.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawValidatorStake proto.InternalMessageInfo

func (m *MsgWithdrawValidatorStake) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgWithdrawValidatorStake) GetValId() uint64 {
	if m != nil {
		return m.ValId
	}
	return 0
}

// MsgWithdrawValidatorStakeResponse defines the response for
// MsgWithdrawValidatorStake.
type MsgWithdrawValidatorStakeResponse struct {
}

func (m *MsgWithdrawValidatorStakeResponse) Reset()         { *m = MsgWithdrawValidatorStakeResponse{} }
func (m *MsgWithdrawValidatorStakeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawValidatorStakeResponse) ProtoMessage()    {}
func (*MsgWithdrawValidatorStakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{3}
}
func (m *MsgWithdrawValidatorStakeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawValidatorStakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawValidatorStakeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawValidatorStakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawValidatorStakeResponse.Merge(m, src)
}
func (m *MsgWithdrawValidatorStakeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawValidatorStakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawValidatorStakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawValidatorStakeResponse proto.InternalMessageInfo

// MsgDelegateGold defines a user GOLD delegation to a validator.
type MsgDelegateGold struct {
	From   string                `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	ValId  uint64                `protobuf:"varint,2,opt,name=val_id,json=valId,proto3" json:"val_id,omitempty"`
	Amount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *MsgDelegateGold) Reset()         { *m = MsgDelegateGold{} }
func (m *MsgDelegateGold) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateGold) ProtoMessage()    {}
func (*MsgDelegateGold) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{4}
}
func (m *MsgDelegateGold) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelegateGold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelegateGold.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelegateGold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelegateGold.Merge(m, src)
}
func (m *MsgDelegateGold) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelegateGold) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelegateGold.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelegateGold proto.InternalMessageInfo

func (m *MsgDelegateGold) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgDelegateGold) GetValId() uint64 {
	if m != nil {
		return m.ValId
	}
	return 0
}

// MsgDelegateGoldResponse defines the response for MsgDelegateGold.
type MsgDelegateGoldResponse struct {
}

func (m *MsgDelegateGoldResponse) Reset()         { *m = MsgDelegateGoldResponse{} }
func (m *MsgDelegateGoldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDelegateGoldResponse) ProtoMessage()    {}
func (*MsgDelegateGoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{5}
}
func (m *MsgDelegateGoldResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDelegateGoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDelegateGoldResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDelegateGoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDelegateGoldResponse.Merge(m, src)
}
func (m *MsgDelegateGoldResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDelegateGoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDelegateGoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDelegateGoldResponse proto.InternalMessageInfo

// MsgUndelegateGold defines a user GOLD undelegation from a validator.
type MsgUndelegateGold struct {
	From   string                `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	ValId  uint64                `protobuf:"varint,2,opt,name=val_id,json=valId,proto3" json:"val_id,omitempty"`
	Amount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *MsgUndelegateGold) Reset()         { *m = MsgUndelegateGold{} }
func (m *MsgUndelegateGold) String() string { return proto.CompactTextString(m) }
func (*MsgUndelegateGold) ProtoMessage()    {}
func (*MsgUndelegateGold) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{6}
}
func (m *MsgUndelegateGold) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUndelegateGold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUndelegateGold.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUndelegateGold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUndelegateGold.Merge(m, src)
}
func (m *MsgUndelegateGold) XXX_Size() int {
	return m.Size()
}
func (m *MsgUndelegateGold) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUndelegateGold.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUndelegateGold proto.InternalMessageInfo

func (m *MsgUndelegateGold) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *MsgUndelegateGold) GetValId() uint64 {
	if m != nil {
		return m.ValId
	}
	return 0
}

// MsgUndelegateGoldResponse defines the response for MsgUndelegateGold.
type MsgUndelegateGoldResponse struct {
}

func (m *MsgUndelegateGoldResponse) Reset()         { *m = MsgUndelegateGoldResponse{} }
func (m *MsgUndelegateGoldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUndelegateGoldResponse) ProtoMessage()    {}
func (*MsgUndelegateGoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ff98efd7592e442, []int{7}
}
func (m *MsgUndelegateGoldResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUndelegateGoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUndelegateGoldResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUndelegateGoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUndelegateGoldResponse.Merge(m, src)
}
func (m *MsgUndelegateGoldResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUndelegateGoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUndelegateGoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUndelegateGoldResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgApproveValidator)(nil), "giltconsensusv2.stake.MsgApproveValidator")
	proto.RegisterType((*MsgApproveValidatorResponse)(nil), "giltconsensusv2.stake.MsgApproveValidatorResponse")
	proto.RegisterType((*MsgWithdrawValidatorStake)(nil), "giltconsensusv2.stake.MsgWithdrawValidatorStake")
	proto.RegisterType((*MsgWithdrawValidatorStakeResponse)(nil), "giltconsensusv2.stake.MsgWithdrawValidatorStakeResponse")
	proto.RegisterType((*MsgDelegateGold)(nil), "giltconsensusv2.stake.MsgDelegateGold")
	proto.RegisterType((*MsgDelegateGoldResponse)(nil), "giltconsensusv2.stake.MsgDelegateGoldResponse")
	proto.RegisterType((*MsgUndelegateGold)(nil), "giltconsensusv2.stake.MsgUndelegateGold")
	proto.RegisterType((*MsgUndelegateGoldResponse)(nil), "giltconsensusv2.stake.MsgUndelegateGoldResponse")
}

func init() { proto.RegisterFile("giltconsensusv2/stake/tx.proto", fileDescriptor_1ff98efd7592e442) }

var fileDescriptor_1ff98efd7592e442 = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0x98, 0x26, 0xea, 0x10, 0xfa, 0x63, 0x6d, 0xed, 0x76, 0xdb, 0x6e, 0xea, 0x0a, 0x12,
	0x23, 0xdd, 0x4d, 0xe3, 0x45, 0x73, 0x91, 0x16, 0x4b, 0x2d, 0x25, 0x20, 0x2d, 0x2a, 0x78, 0x59,
	0x26, 0xd9, 0xe9, 0x64, 0xe8, 0xee, 0xce, 0xb2, 0x33, 0x89, 0xe9, 0x4d, 0xc4, 0x83, 0x78, 0xf2,
	0x4f, 0xe8, 0xb1, 0xc7, 0x82, 0xfe, 0x11, 0x3d, 0x16, 0xf1, 0x20, 0x82, 0x45, 0xda, 0x43, 0xfd,
	0x33, 0x64, 0x77, 0x93, 0x6d, 0x53, 0x77, 0x21, 0x42, 0x0f, 0x5e, 0x92, 0xdd, 0xf7, 0x7d, 0xef,
	0x7d, 0xf3, 0xbd, 0x7d, 0x33, 0x03, 0x55, 0x42, 0x6d, 0xd1, 0x64, 0x2e, 0xc7, 0x2e, 0x6f, 0xf3,
	0x4e, 0xd5, 0xe0, 0x02, 0xed, 0x60, 0x43, 0x74, 0x75, 0xcf, 0x67, 0x82, 0x49, 0x53, 0x97, 0x70,
	0x3d, 0xc4, 0x95, 0x49, 0xc2, 0x08, 0x0b, 0x19, 0x46, 0xf0, 0x14, 0x91, 0x95, 0x99, 0x26, 0xe3,
	0x0e, 0xe3, 0x66, 0x04, 0x44, 0x2f, 0x3d, 0x68, 0x3a, 0x7a, 0x33, 0x1c, 0x4e, 0x8c, 0xce, 0x52,
	0xf0, 0xd7, 0x03, 0x26, 0x90, 0x43, 0x5d, 0x66, 0x84, 0xbf, 0x51, 0x48, 0xdb, 0xcf, 0xc2, 0x5b,
	0x75, 0x4e, 0x96, 0x3d, 0xcf, 0x67, 0x1d, 0xfc, 0x12, 0xd9, 0xd4, 0x42, 0x82, 0xf9, 0xd2, 0x12,
	0x1c, 0xd9, 0xf6, 0x99, 0x23, 0x83, 0x05, 0x50, 0xba, 0xb9, 0x32, 0xff, 0xf5, 0xcb, 0xe2, 0x64,
	0x4f, 0x63, 0xd9, 0xb2, 0x7c, 0xcc, 0xf9, 0x96, 0xf0, 0xa9, 0x4b, 0xf6, 0xcf, 0x0e, 0xca, 0x60,
	0x33, 0xa4, 0x4a, 0x73, 0x30, 0xdf, 0x41, 0xb6, 0x49, 0x2d, 0xf9, 0xda, 0x02, 0x28, 0x8d, 0xac,
	0xe4, 0x22, 0x30, 0xd7, 0x41, 0xf6, 0xba, 0x25, 0x3d, 0x86, 0x37, 0x98, 0x87, 0xfd, 0xa0, 0xb8,
	0x9c, 0x1d, 0xa6, 0x68, 0x4c, 0x97, 0x2a, 0x70, 0x1c, 0x35, 0x05, 0xed, 0x20, 0x41, 0x99, 0x6b,
	0x62, 0x8f, 0x35, 0x5b, 0xf2, 0xc8, 0x45, 0x89, 0xb1, 0x73, 0x78, 0x35, 0x40, 0xa5, 0x67, 0x70,
	0xd4, 0x41, 0x5d, 0x33, 0xe8, 0xa7, 0x19, 0x36, 0x51, 0xce, 0x85, 0x92, 0xda, 0xe1, 0x71, 0x31,
	0xf3, 0xe3, 0xb8, 0x38, 0x15, 0xc9, 0x72, 0x6b, 0x47, 0xa7, 0xcc, 0x70, 0x90, 0x68, 0xe9, 0xeb,
	0xae, 0x88, 0x8a, 0x15, 0x1c, 0xd4, 0x5d, 0xa3, 0xb6, 0xd8, 0x0a, 0xf2, 0xa4, 0x07, 0x70, 0x94,
	0x53, 0xe2, 0x62, 0xdf, 0xf4, 0xda, 0x0d, 0x73, 0x07, 0xef, 0xca, 0xf9, 0x05, 0x50, 0x2a, 0xf4,
	0x95, 0x0b, 0x11, 0xf8, 0xbc, 0xdd, 0xd8, 0xc0, 0xbb, 0xd2, 0x2c, 0xcc, 0xb9, 0xcc, 0x6d, 0x62,
	0xf9, 0xfa, 0x40, 0x03, 0xc2, 0x58, 0xed, 0xc9, 0x87, 0xbd, 0x22, 0xf8, 0xbd, 0x57, 0xcc, 0xbc,
	0x3b, 0x3b, 0x28, 0x87, 0x1d, 0xfb, 0x78, 0x76, 0x50, 0xbe, 0x9f, 0x3c, 0x13, 0x09, 0x9f, 0x44,
	0x9b, 0x87, 0xb3, 0x09, 0xe1, 0x4d, 0xcc, 0xbd, 0x20, 0x5d, 0xfb, 0x0c, 0xe0, 0x4c, 0x9d, 0x93,
	0x57, 0x54, 0xb4, 0x2c, 0x1f, 0xbd, 0x89, 0x09, 0x91, 0x8f, 0xab, 0xfe, 0x9e, 0xb5, 0xd5, 0x44,
	0x3b, 0x46, 0xaa, 0x9d, 0xe4, 0x75, 0x69, 0x77, 0xe1, 0x9d, 0x54, 0x30, 0xb6, 0x76, 0x04, 0xe0,
	0x58, 0x9d, 0x93, 0xa7, 0xd8, 0xc6, 0x04, 0x09, 0xbc, 0xc6, 0x6c, 0xeb, 0xea, 0x07, 0xb4, 0x06,
	0xf3, 0xc8, 0x61, 0x6d, 0x57, 0xf4, 0xc6, 0x73, 0x98, 0x59, 0xe9, 0x65, 0xd4, 0x2a, 0x89, 0xcd,
	0x50, 0x82, 0x66, 0x9c, 0x77, 0xe0, 0xe2, 0xf2, 0xb5, 0x19, 0x38, 0x7d, 0x29, 0x14, 0xbb, 0xfd,
	0x06, 0xe0, 0x44, 0x9d, 0x93, 0x17, 0xae, 0xf5, 0xdf, 0xfa, 0xad, 0x26, 0xfa, 0x9d, 0x1b, 0xf4,
	0x3b, 0x68, 0x40, 0x9b, 0x0d, 0xc7, 0x73, 0x30, 0xd8, 0xf7, 0x5c, 0xfd, 0x99, 0x85, 0xd9, 0x3a,
	0x27, 0x92, 0x0f, 0xc7, 0xff, 0x3a, 0x8a, 0xca, 0x7a, 0xe2, 0xb9, 0xa8, 0x27, 0x6c, 0x06, 0xa5,
	0x3a, 0x3c, 0xb7, 0xaf, 0x2d, 0xbd, 0x07, 0xf0, 0x76, 0xca, 0xae, 0xa9, 0xa4, 0x97, 0x4b, 0xce,
	0x50, 0x1e, 0xfd, 0x6b, 0x46, 0xbc, 0x8c, 0x6d, 0x58, 0x18, 0x18, 0xf0, 0x7b, 0xe9, 0x95, 0x2e,
	0xf2, 0x14, 0x7d, 0x38, 0x5e, 0xac, 0x63, 0xc3, 0xd1, 0x4b, 0xa3, 0x55, 0x4a, 0xaf, 0x30, 0xc8,
	0x54, 0x2a, 0xc3, 0x32, 0xfb, 0x6a, 0x4a, 0xee, 0x6d, 0x30, 0x38, 0x2b, 0x1b, 0x87, 0x27, 0x2a,
	0x38, 0x3a, 0x51, 0xc1, 0xaf, 0x13, 0x15, 0x7c, 0x3a, 0x55, 0x33, 0x47, 0xa7, 0x6a, 0xe6, 0xfb,
	0xa9, 0x9a, 0x79, 0xbd, 0x44, 0xa8, 0x68, 0xb5, 0x1b, 0x7a, 0x93, 0x39, 0xd1, 0xe1, 0xd1, 0x42,
	0xd4, 0x0d, 0x9f, 0x16, 0x63, 0x1d, 0xa3, 0xdb, 0xbf, 0x2a, 0x77, 0x3d, 0xcc, 0x1b, 0xf9, 0xf0,
	0xea, 0x7a, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xc0, 0xd9, 0x8f, 0x50, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ApproveValidator casts a validator vote for a validator candidate proposal.
	ApproveValidator(ctx context.Context, in *MsgApproveValidator, opts ...grpc.CallOption) (*MsgApproveValidatorResponse, error)
	// WithdrawValidatorStake releases self-bonded GILT after the validator's
	// unbonding period has completed.
	WithdrawValidatorStake(ctx context.Context, in *MsgWithdrawValidatorStake, opts ...grpc.CallOption) (*MsgWithdrawValidatorStakeResponse, error)
	// DelegateGold escrows GOLD behind a validator for reward-weight accounting.
	DelegateGold(ctx context.Context, in *MsgDelegateGold, opts ...grpc.CallOption) (*MsgDelegateGoldResponse, error)
	// UndelegateGold releases escrowed GOLD from validator reward-weight
	// accounting.
	UndelegateGold(ctx context.Context, in *MsgUndelegateGold, opts ...grpc.CallOption) (*MsgUndelegateGoldResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ApproveValidator(ctx context.Context, in *MsgApproveValidator, opts ...grpc.CallOption) (*MsgApproveValidatorResponse, error) {
	out := new(MsgApproveValidatorResponse)
	err := c.cc.Invoke(ctx, "/giltconsensusv2.stake.Msg/ApproveValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawValidatorStake(ctx context.Context, in *MsgWithdrawValidatorStake, opts ...grpc.CallOption) (*MsgWithdrawValidatorStakeResponse, error) {
	out := new(MsgWithdrawValidatorStakeResponse)
	err := c.cc.Invoke(ctx, "/giltconsensusv2.stake.Msg/WithdrawValidatorStake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DelegateGold(ctx context.Context, in *MsgDelegateGold, opts ...grpc.CallOption) (*MsgDelegateGoldResponse, error) {
	out := new(MsgDelegateGoldResponse)
	err := c.cc.Invoke(ctx, "/giltconsensusv2.stake.Msg/DelegateGold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UndelegateGold(ctx context.Context, in *MsgUndelegateGold, opts ...grpc.CallOption) (*MsgUndelegateGoldResponse, error) {
	out := new(MsgUndelegateGoldResponse)
	err := c.cc.Invoke(ctx, "/giltconsensusv2.stake.Msg/UndelegateGold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ApproveValidator casts a validator vote for a validator candidate proposal.
	ApproveValidator(context.Context, *MsgApproveValidator) (*MsgApproveValidatorResponse, error)
	// WithdrawValidatorStake releases self-bonded GILT after the validator's
	// unbonding period has completed.
	WithdrawValidatorStake(context.Context, *MsgWithdrawValidatorStake) (*MsgWithdrawValidatorStakeResponse, error)
	// DelegateGold escrows GOLD behind a validator for reward-weight accounting.
	DelegateGold(context.Context, *MsgDelegateGold) (*MsgDelegateGoldResponse, error)
	// UndelegateGold releases escrowed GOLD from validator reward-weight
	// accounting.
	UndelegateGold(context.Context, *MsgUndelegateGold) (*MsgUndelegateGoldResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ApproveValidator(ctx context.Context, req *MsgApproveValidator) (*MsgApproveValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveValidator not implemented")
}
func (*UnimplementedMsgServer) WithdrawValidatorStake(ctx context.Context, req *MsgWithdrawValidatorStake) (*MsgWithdrawValidatorStakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawValidatorStake not implemented")
}
func (*UnimplementedMsgServer) DelegateGold(ctx context.Context, req *MsgDelegateGold) (*MsgDelegateGoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateGold not implemented")
}
func (*UnimplementedMsgServer) UndelegateGold(ctx context.Context, req *MsgUndelegateGold) (*MsgUndelegateGoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndelegateGold not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ApproveValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveValidator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/giltconsensusv2.stake.Msg/ApproveValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveValidator(ctx, req.(*MsgApproveValidator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawValidatorStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawValidatorStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawValidatorStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/giltconsensusv2.stake.Msg/WithdrawValidatorStake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawValidatorStake(ctx, req.(*MsgWithdrawValidatorStake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DelegateGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateGold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelegateGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/giltconsensusv2.stake.Msg/DelegateGold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelegateGold(ctx, req.(*MsgDelegateGold))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UndelegateGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUndelegateGold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UndelegateGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/giltconsensusv2.stake.Msg/UndelegateGold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UndelegateGold(ctx, req.(*MsgUndelegateGold))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "giltconsensusv2.stake.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApproveValidator",
			Handler:    _Msg_ApproveValidator_Handler,
		},
		{
			MethodName: "WithdrawValidatorStake",
			Handler:    _Msg_WithdrawValidatorStake_Handler,
		},
		{
			MethodName: "DelegateGold",
			Handler:    _Msg_DelegateGold_Handler,
		},
		{
			MethodName: "UndelegateGold",
			Handler:    _Msg_UndelegateGold_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "giltconsensusv2/stake/tx.proto",
}

func (m *MsgApproveValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x38
	}
	if len(m.SignerPubKey) > 0 {
		i -= len(m.SignerPubKey)
		copy(dAtA[i:], m.SignerPubKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerPubKey)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.MaxGiltStake.Size()
		i -= size
		if _, err := m.MaxGiltStake.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.ActivationEpoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ActivationEpoch))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ValId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ValId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgApproveValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawValidatorStake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawValidatorStake) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawValidatorStake) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ValId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawValidatorStakeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawValidatorStakeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawValidatorStakeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDelegateGold) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelegateGold) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelegateGold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.ValId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ValId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDelegateGoldResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDelegateGoldResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDelegateGoldResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUndelegateGold) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUndelegateGold) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUndelegateGold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.ValId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ValId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUndelegateGoldResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUndelegateGoldResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUndelegateGoldResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgApproveValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ValId != 0 {
		n += 1 + sovTx(uint64(m.ValId))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ActivationEpoch != 0 {
		n += 1 + sovTx(uint64(m.ActivationEpoch))
	}
	l = m.MaxGiltStake.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.SignerPubKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovTx(uint64(m.Nonce))
	}
	return n
}

func (m *MsgApproveValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawValidatorStake) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ValId != 0 {
		n += 1 + sovTx(uint64(m.ValId))
	}
	return n
}

func (m *MsgWithdrawValidatorStakeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDelegateGold) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ValId != 0 {
		n += 1 + sovTx(uint64(m.ValId))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgDelegateGoldResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUndelegateGold) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ValId != 0 {
		n += 1 + sovTx(uint64(m.ValId))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUndelegateGoldResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgApproveValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValId", wireType)
			}
			m.ValId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationEpoch", wireType)
			}
			m.ActivationEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGiltStake", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxGiltStake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerPubKey = append(m.SignerPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.SignerPubKey == nil {
				m.SignerPubKey = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApproveValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawValidatorStake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawValidatorStake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawValidatorStake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValId", wireType)
			}
			m.ValId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawValidatorStakeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawValidatorStakeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawValidatorStakeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelegateGold) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelegateGold: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelegateGold: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValId", wireType)
			}
			m.ValId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDelegateGoldResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDelegateGoldResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDelegateGoldResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUndelegateGold) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUndelegateGold: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUndelegateGold: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValId", wireType)
			}
			m.ValId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUndelegateGoldResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUndelegateGoldResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUndelegateGoldResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
