// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: giltconsensusv2/sidetxs/vote_ext.proto

package sidetxs

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Vote represents a validator's decision on a side transaction.
type Vote int32

const (
	Vote_UNSPECIFIED Vote = 0
	Vote_VOTE_YES    Vote = 1
	Vote_VOTE_NO     Vote = 2
)

var Vote_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "VOTE_YES",
	2: "VOTE_NO",
}

var Vote_value = map[string]int32{
	"UNSPECIFIED": 0,
	"VOTE_YES":    1,
	"VOTE_NO":     2,
}

func (x Vote) String() string {
	return proto.EnumName(Vote_name, int32(x))
}

func (Vote) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8ccbaa5a811a787, []int{0}
}

// VoteExtension contains additional data included by validators in their votes.
// Introduced in ABCI++, vote extensions allow validators to include
// supplementary information like side transaction results.
type VoteExtension struct {
	// Hash of the block this vote extension is for.
	BlockHash []byte `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Height of the block this vote extension is for.
	Height int64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Results of side transaction validation by this validator.
	SideTxResponses []SideTxResponse `protobuf:"bytes,3,rep,name=side_tx_responses,json=sideTxResponses,proto3" json:"side_tx_responses"`
}

func (m *VoteExtension) Reset()         { *m = VoteExtension{} }
func (m *VoteExtension) String() string { return proto.CompactTextString(m) }
func (*VoteExtension) ProtoMessage()    {}
func (*VoteExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8ccbaa5a811a787, []int{0}
}
func (m *VoteExtension) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteExtension.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteExtension.Merge(m, src)
}
func (m *VoteExtension) XXX_Size() int {
	return m.Size()
}
func (m *VoteExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteExtension.DiscardUnknown(m)
}

var xxx_messageInfo_VoteExtension proto.InternalMessageInfo

func (m *VoteExtension) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *VoteExtension) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VoteExtension) GetSideTxResponses() []SideTxResponse {
	if m != nil {
		return m.SideTxResponses
	}
	return nil
}

// SideTxResponse contains a validator's vote on a side transaction.
type SideTxResponse struct {
	// Hash of the side transaction being voted on.
	TxHash []byte `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// The validator's vote (yes or no).
	Result Vote `protobuf:"varint,2,opt,name=result,proto3,enum=giltconsensusv2.sidetxs.Vote" json:"result,omitempty"`
}

func (m *SideTxResponse) Reset()         { *m = SideTxResponse{} }
func (m *SideTxResponse) String() string { return proto.CompactTextString(m) }
func (*SideTxResponse) ProtoMessage()    {}
func (*SideTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8ccbaa5a811a787, []int{1}
}
func (m *SideTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SideTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SideTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SideTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SideTxResponse.Merge(m, src)
}
func (m *SideTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *SideTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SideTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SideTxResponse proto.InternalMessageInfo

func (m *SideTxResponse) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *SideTxResponse) GetResult() Vote {
	if m != nil {
		return m.Result
	}
	return Vote_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("giltconsensusv2.sidetxs.Vote", Vote_name, Vote_value)
	proto.RegisterType((*VoteExtension)(nil), "giltconsensusv2.sidetxs.VoteExtension")
	proto.RegisterType((*SideTxResponse)(nil), "giltconsensusv2.sidetxs.SideTxResponse")
}

func init() {
	proto.RegisterFile("giltconsensusv2/sidetxs/vote_ext.proto", fileDescriptor_c8ccbaa5a811a787)
}

var fileDescriptor_c8ccbaa5a811a787 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0x3a, 0x41,
	0x18, 0xc7, 0x77, 0xf4, 0xf7, 0x5b, 0x73, 0x34, 0xff, 0x0c, 0x41, 0x22, 0xb8, 0x89, 0x44, 0x89,
	0xd1, 0x2e, 0x6c, 0xd7, 0x4e, 0xd6, 0x46, 0x5e, 0x34, 0xd4, 0x84, 0x3a, 0xb4, 0xac, 0x3a, 0xec,
	0x0e, 0xe9, 0x8e, 0x38, 0xa3, 0xcc, 0xcb, 0xe8, 0x65, 0x74, 0xec, 0xd0, 0x8b, 0xf0, 0xe8, 0xb1,
	0x53, 0x84, 0x1e, 0x7a, 0x1b, 0xb1, 0xb3, 0x2a, 0x18, 0x79, 0x19, 0x9e, 0xf9, 0x3e, 0x9f, 0x67,
	0xf8, 0x30, 0x0f, 0x3c, 0x71, 0xc9, 0x80, 0xf7, 0xa8, 0xcf, 0xb0, 0xcf, 0x26, 0x6c, 0x6a, 0x1a,
	0x8c, 0xf4, 0x31, 0x17, 0xcc, 0x98, 0x52, 0x8e, 0x6d, 0x2c, 0xb8, 0x3e, 0x1a, 0x53, 0x4e, 0xd1,
	0xe1, 0x2f, 0x4e, 0x5f, 0x71, 0xf9, 0xac, 0x33, 0x24, 0x3e, 0x35, 0xe4, 0x19, 0xb2, 0xf9, 0x03,
	0x97, 0xba, 0x54, 0x96, 0x46, 0x50, 0x85, 0x69, 0xe9, 0x1d, 0xc0, 0xfd, 0x0e, 0xe5, 0xd8, 0x12,
	0x1c, 0xfb, 0x8c, 0x50, 0x1f, 0x1d, 0x43, 0xd8, 0x1d, 0xd0, 0xde, 0xb3, 0xed, 0x39, 0xcc, 0xcb,
	0x81, 0x22, 0x28, 0x27, 0xab, 0xff, 0x5f, 0xbf, 0xdf, 0x2a, 0xa0, 0x19, 0x97, 0x8d, 0x5b, 0x87,
	0x79, 0xa8, 0x00, 0x55, 0x0f, 0x13, 0xd7, 0xe3, 0xb9, 0x48, 0x11, 0x94, 0xa3, 0x6b, 0x62, 0x15,
	0xa2, 0x27, 0x98, 0x0d, 0x54, 0x6c, 0x2e, 0xec, 0x31, 0x66, 0xa3, 0xc0, 0x90, 0xe5, 0xa2, 0xc5,
	0x68, 0x39, 0x61, 0x9e, 0xea, 0x3b, 0xa4, 0xf5, 0x16, 0xe9, 0xe3, 0xb6, 0x68, 0xae, 0xf8, 0x6a,
	0x7c, 0xf6, 0x79, 0xa4, 0x84, 0xcf, 0xa6, 0xd9, 0x56, 0x8b, 0x95, 0x7c, 0x98, 0xda, 0xa6, 0x91,
	0x06, 0x63, 0x5c, 0xfc, 0xe1, 0xac, 0x72, 0x21, 0x85, 0x2f, 0xa1, 0x3a, 0xc6, 0x6c, 0x32, 0x08,
	0x85, 0x53, 0x66, 0x61, 0xa7, 0x46, 0xf0, 0x1d, 0x9b, 0xe9, 0x70, 0xa6, 0x62, 0xc2, 0x7f, 0x41,
	0x8c, 0xd2, 0x30, 0x71, 0x5f, 0x6f, 0xdd, 0x59, 0x57, 0xb5, 0x9b, 0x9a, 0x75, 0x9d, 0x51, 0x50,
	0x12, 0xee, 0x75, 0x1a, 0x6d, 0xcb, 0x7e, 0xb0, 0x5a, 0x19, 0x80, 0x12, 0x30, 0x26, 0x6f, 0xf5,
	0x46, 0x26, 0x52, 0xb5, 0x66, 0x0b, 0x0d, 0xcc, 0x17, 0x1a, 0xf8, 0x5a, 0x68, 0xe0, 0x65, 0xa9,
	0x29, 0xf3, 0xa5, 0xa6, 0x7c, 0x2c, 0x35, 0xe5, 0xf1, 0xcc, 0x25, 0xdc, 0x9b, 0x74, 0xf5, 0x1e,
	0x1d, 0x1a, 0xd2, 0xc2, 0x73, 0x88, 0x2f, 0xab, 0xf3, 0x8d, 0xd0, 0x7a, 0xe5, 0x5d, 0x55, 0x2e,
	0xea, 0xe2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x56, 0x41, 0xb2, 0x14, 0x02, 0x00, 0x00,
}

func (m *VoteExtension) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteExtension) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteExtension) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SideTxResponses) > 0 {
		for iNdEx := len(m.SideTxResponses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SideTxResponses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVoteExt(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Height != 0 {
		i = encodeVarintVoteExt(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintVoteExt(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SideTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SideTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SideTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != 0 {
		i = encodeVarintVoteExt(dAtA, i, uint64(m.Result))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintVoteExt(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoteExt(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoteExt(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VoteExtension) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovVoteExt(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovVoteExt(uint64(m.Height))
	}
	if len(m.SideTxResponses) > 0 {
		for _, e := range m.SideTxResponses {
			l = e.Size()
			n += 1 + l + sovVoteExt(uint64(l))
		}
	}
	return n
}

func (m *SideTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovVoteExt(uint64(l))
	}
	if m.Result != 0 {
		n += 1 + sovVoteExt(uint64(m.Result))
	}
	return n
}

func sovVoteExt(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoteExt(x uint64) (n int) {
	return sovVoteExt(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VoteExtension) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteExt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteExtension: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteExtension: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExt
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = append(m.BlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockHash == nil {
				m.BlockHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SideTxResponses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVoteExt
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SideTxResponses = append(m.SideTxResponses, SideTxResponse{})
			if err := m.SideTxResponses[len(m.SideTxResponses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVoteExt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteExt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SideTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteExt
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SideTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SideTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExt
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExt
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			m.Result = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Result |= Vote(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVoteExt(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteExt
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoteExt(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoteExt
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExt
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoteExt
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoteExt
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoteExt
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoteExt        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoteExt          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoteExt = fmt.Errorf("proto: unexpected end of group")
)
