// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: giltconsensusv2/stake/tx.proto

package stake

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_ApproveValidator_FullMethodName       = "/giltconsensusv2.stake.Msg/ApproveValidator"
	Msg_WithdrawValidatorStake_FullMethodName = "/giltconsensusv2.stake.Msg/WithdrawValidatorStake"
	Msg_DelegateGold_FullMethodName           = "/giltconsensusv2.stake.Msg/DelegateGold"
	Msg_UndelegateGold_FullMethodName         = "/giltconsensusv2.stake.Msg/UndelegateGold"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the gRPC message service for the stake module.
type MsgClient interface {
	// ApproveValidator casts a validator vote for a validator candidate proposal.
	ApproveValidator(ctx context.Context, in *MsgApproveValidator, opts ...grpc.CallOption) (*MsgApproveValidatorResponse, error)
	// WithdrawValidatorStake releases self-bonded GILT after the validator's
	// unbonding period has completed.
	WithdrawValidatorStake(ctx context.Context, in *MsgWithdrawValidatorStake, opts ...grpc.CallOption) (*MsgWithdrawValidatorStakeResponse, error)
	// DelegateGold escrows GOLD behind a validator for reward-weight accounting.
	DelegateGold(ctx context.Context, in *MsgDelegateGold, opts ...grpc.CallOption) (*MsgDelegateGoldResponse, error)
	// UndelegateGold releases escrowed GOLD from validator reward-weight
	// accounting.
	UndelegateGold(ctx context.Context, in *MsgUndelegateGold, opts ...grpc.CallOption) (*MsgUndelegateGoldResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ApproveValidator(ctx context.Context, in *MsgApproveValidator, opts ...grpc.CallOption) (*MsgApproveValidatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgApproveValidatorResponse)
	err := c.cc.Invoke(ctx, Msg_ApproveValidator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawValidatorStake(ctx context.Context, in *MsgWithdrawValidatorStake, opts ...grpc.CallOption) (*MsgWithdrawValidatorStakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgWithdrawValidatorStakeResponse)
	err := c.cc.Invoke(ctx, Msg_WithdrawValidatorStake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DelegateGold(ctx context.Context, in *MsgDelegateGold, opts ...grpc.CallOption) (*MsgDelegateGoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDelegateGoldResponse)
	err := c.cc.Invoke(ctx, Msg_DelegateGold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UndelegateGold(ctx context.Context, in *MsgUndelegateGold, opts ...grpc.CallOption) (*MsgUndelegateGoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUndelegateGoldResponse)
	err := c.cc.Invoke(ctx, Msg_UndelegateGold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the gRPC message service for the stake module.
type MsgServer interface {
	// ApproveValidator casts a validator vote for a validator candidate proposal.
	ApproveValidator(context.Context, *MsgApproveValidator) (*MsgApproveValidatorResponse, error)
	// WithdrawValidatorStake releases self-bonded GILT after the validator's
	// unbonding period has completed.
	WithdrawValidatorStake(context.Context, *MsgWithdrawValidatorStake) (*MsgWithdrawValidatorStakeResponse, error)
	// DelegateGold escrows GOLD behind a validator for reward-weight accounting.
	DelegateGold(context.Context, *MsgDelegateGold) (*MsgDelegateGoldResponse, error)
	// UndelegateGold releases escrowed GOLD from validator reward-weight
	// accounting.
	UndelegateGold(context.Context, *MsgUndelegateGold) (*MsgUndelegateGoldResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) ApproveValidator(context.Context, *MsgApproveValidator) (*MsgApproveValidatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveValidator not implemented")
}
func (UnimplementedMsgServer) WithdrawValidatorStake(context.Context, *MsgWithdrawValidatorStake) (*MsgWithdrawValidatorStakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawValidatorStake not implemented")
}
func (UnimplementedMsgServer) DelegateGold(context.Context, *MsgDelegateGold) (*MsgDelegateGoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateGold not implemented")
}
func (UnimplementedMsgServer) UndelegateGold(context.Context, *MsgUndelegateGold) (*MsgUndelegateGoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndelegateGold not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_ApproveValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveValidator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ApproveValidator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveValidator(ctx, req.(*MsgApproveValidator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawValidatorStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawValidatorStake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawValidatorStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_WithdrawValidatorStake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawValidatorStake(ctx, req.(*MsgWithdrawValidatorStake))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DelegateGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateGold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelegateGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DelegateGold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelegateGold(ctx, req.(*MsgDelegateGold))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UndelegateGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUndelegateGold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UndelegateGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UndelegateGold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UndelegateGold(ctx, req.(*MsgUndelegateGold))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "giltconsensusv2.stake.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApproveValidator",
			Handler:    _Msg_ApproveValidator_Handler,
		},
		{
			MethodName: "WithdrawValidatorStake",
			Handler:    _Msg_WithdrawValidatorStake_Handler,
		},
		{
			MethodName: "DelegateGold",
			Handler:    _Msg_DelegateGold_Handler,
		},
		{
			MethodName: "UndelegateGold",
			Handler:    _Msg_UndelegateGold_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "giltconsensusv2/stake/tx.proto",
}
